# Copyright (c) 2025 Contributors to the Eclipse Foundation.
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"
    #csrf_protection: true
    http_method_override: false
    csrf_protection: false
    handle_all_throwables: true
    uid:
        default_uuid_version: 7
        time_based_uuid_version: 7

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    serializer:
        circular_reference_handler: carve_api.serializer.circular_reference_handler
        default_context:
            datetime_timezone: 'UTC'

    trusted_proxies: "%env(TRUSTED_PROXIES)%"
    #using "%env()%" is not possible due to bug in symfony with env arrays e.g. %env(csv:XXX)%
    trusted_headers: "%PARAMETER_TRUSTED_HEADERS%"
    trusted_hosts: "%PARAMETER_TRUSTED_HOSTS%"

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
