# Copyright (c) 2025 Contributors to the Eclipse Foundation.
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: "%env(int:SESSION_TIMEOUT)%"
    ttl_update: true
    return_expiration: true
    token_parameter_name: refreshToken
    return_expiration_parameter_name: refreshTokenExpiration
