name: "Run PHPUnit tests"
description: "Run PHPUnit tests"

inputs:
    version:
        description: "Image version"
        required: true
    group:
        description: "Test group"
        required: true

runs:
    using: "composite"
    steps:
        - name: Run tests for group "${{ inputs.group }}"
          shell: bash
          run: |
              echo "APPLICATION_VERSION=${{ inputs.version }}" >> docker/deployments/test/.env
              docker compose -f docker/deployments/test/compose.yaml up -d
              docker/deployments/test/wait-until-ready.sh
              docker compose -f docker/deployments/test/compose.yaml exec application php bin/phpunit --group "${{ inputs.group }}"
              docker compose -f docker/deployments/test/compose.yaml down
