<?php

// Copyright (c) 2025 Contributors to the Eclipse Foundation.
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache License, Version 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0

declare(strict_types=1);

namespace Tests\Suites\DeviceCommunication\DeviceSecretsAndCertificates;

use App\Entity\Device;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Group;
use Tests\DataFixtures as TestFixtures;
use Tests\Utilities\Builder\DeviceCommunicationTestMatrixBuilder;
use Tests\Utilities\DeviceCommunicationAbstract\AbstractDeviceCommunicationTestCase;
use Tests\Utilities\DeviceCommunicationAbstract\Trait\DeviceSecretsAndCertificatesTrait;
use Tests\Utilities\DeviceCommunicationApiClient\Model\DeviceModel;

// This class tests enabled device with empty template components
// It checks that the device can be created with the correct secrets and certificates based on the device type configuration

class EmptyTemplateComponentsTest extends AbstractDeviceCommunicationTestCase
{
    use DeviceSecretsAndCertificatesTrait;

    public static function getFixtureGroups(): array
    {
        return \array_merge(
            parent::getFixtureGroups(),
            [
                TestFixtures\DeviceCommunication\DeviceSecretsAndCertificates\DeviceTypeCommunicationProcedureFixtures::class,
                TestFixtures\DeviceCommunication\DeviceSecretsAndCertificates\TemplateCommunicationProcedureFixtures::class,
            ],
        );
    }

    // Data provider combines device types for provider with all possible reinstall flags combinations
    public static function dataProvider(): array
    {
        $templateNames = [
            'noTemplateVersion',
            'emptyProductionTemplateVersion',
            'emptyStagingTemplateVersion',
            'emptyBothTemplateVersion',
            'fullStagingEmptyProductionTemplateVersion',
            'fullStagingTemplateVersion',
            'emptyStagingFullProductionTemplateVersion', // THIS REQUIRES TO SET DEVICE TO STAGING FOR TEST BELOW
        ];

        // Build provider data with device types and reinstall flags combinations cloned for every template name
        // This will result in a matrix of device types, reinstall flags, and template names
        // Each template name will be tested with all device types and reinstall flags combinations
        $providerData = DeviceCommunicationTestMatrixBuilder::withParameter(
            'templateName',
            DeviceCommunicationTestMatrixBuilder::normalizeValues($templateNames),
            DeviceCommunicationTestMatrixBuilder::buildDeviceTypesWithReinstallFlagsMatrix()
        );

        return $providerData;
    }

    #[DataProvider('dataProvider')]
    #[Group('DeviceSecretsAndCertificatesEmptyTemplateComponents')]
    public function testEmptyTemplateComponents(array $deviceTypeConfiguration, array $reinstallFlagsConfiguration, string $templateName): void
    {
        $this->provideDeviceTypeModel($deviceTypeConfiguration, $reinstallFlagsConfiguration);

        $this->executeInitialDeviceCreationRequest();

        $deviceId = $this->getRequiredProvidedEntityParameter(DeviceModel::class, 'id');
        $this->loginApi('admin', 'admin');
        $this->getApiClient()->request(
            uri: '/web/api/device/{id}/enable',
            uriParameters: [
                'id' => $deviceId,
            ],
        );

        $this->provideDeviceState();

        // Asserting correct state of secrets and certificates - only auto-generated certificates should be created
        $this->assertDeviceCertificatesState(false);
        $this->assertDeviceSecretsExists(
            expectAutoGenerated: false,
            expectAll: false,
        );

        $this->updateDeviceWithReinstallFlags($reinstallFlagsConfiguration);

        $this->assignTemplate($templateName);

        if ('emptyStagingFullProductionTemplateVersion' === $templateName) {
            $this->setDeviceToStaging();
        }

        // ? Requesting again to check that device still didn't generate or renew any secrets and certificates
        $this->executeDeviceRequestOnEnabledDevice(expectedDeviceConnectionAmount: 1);

        // Asserting no additional secrets and certificates were created or renewed
        $this->assertDeviceCertificatesState(false);
        $this->assertDeviceSecretsExists(
            expectAutoGenerated: $this->isDeviceSecretsExpected(false),
            expectAll: false,
        );

        $this->assertDeviceReinstallFlags($reinstallFlagsConfiguration);

        // *** Request on all secrets and certificates created - secrets and certificates are outdated - BUT should NOT be renewed */
        $this->updateDeviceWithReinstallFlags($reinstallFlagsConfiguration);
        $this->generateAllDeviceSecrets();
        $this->generateAllDeviceCertificates();

        $this->provideDeviceState();

        $this->makeDeviceSecretsOutdates();
        $this->makeDeviceCertificatesOutdates();

        // ? Requesting again to check that device handled generate or renew of secrets and certificates as expected
        $this->executeDeviceRequestOnEnabledDevice(expectedDeviceConnectionAmount: 2);

        // Asserting no additional secrets and certificates were created or renewed
        $this->assertDeviceCertificatesState($this->isDeviceCertificatesExpected(false));
        $this->assertDeviceSecretsExists(
            expectAutoGenerated: false,
            expectAll: $this->isDeviceSecretsExpected(true),
        );

        $this->assertDeviceSecretsState($this->isDeviceCertificatesExpected(false));
    }
}
