<?php

// Copyright (c) 2025 Contributors to the Eclipse Foundation.
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache License, Version 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0

declare(strict_types=1);

namespace Tests\Suites\DeviceCommunication\DeviceSecretsAndCertificates;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Group;
use Tests\DataFixtures as TestFixtures;
use Tests\Utilities\Builder\DeviceCommunicationTestMatrixBuilder;
use Tests\Utilities\DeviceCommunicationAbstract\AbstractDeviceCommunicationTestCase;
use Tests\Utilities\DeviceCommunicationAbstract\Trait\DeviceSecretsAndCertificatesTrait;
use Tests\Utilities\DeviceCommunicationApiClient\Model\DeviceModel;

// This class tests enabled device with full template components (all valid template components are set)
// It checks that the device can be created with the correct secrets and certificates based on the device type configuration

class FullTemplateComponentsTest extends AbstractDeviceCommunicationTestCase
{
    use DeviceSecretsAndCertificatesTrait;

    public static function getFixtureGroups(): array
    {
        return \array_merge(
            parent::getFixtureGroups(),
            [
                TestFixtures\DeviceCommunication\DeviceSecretsAndCertificates\DeviceTypeCommunicationProcedureFixtures::class,
                TestFixtures\DeviceCommunication\DeviceSecretsAndCertificates\TemplateCommunicationProcedureFixtures::class,
            ],
        );
    }

    // Data provider combines device types for provider with all possible reinstall flags combinations
    public static function dataProvider(): array
    {
        $templateNames = [
            'fullProductionTemplateVersion',
            'fullStagingTemplateVersion', // THIS REQUIRES TO SET DEVICE TO STAGING FOR TEST BELOW
            'fullBothTemplateVersion',
            'fullBothTemplateVersionForStaging', // THIS REQUIRES TO SET DEVICE TO STAGING FOR TEST BELOW
            'fullStagingEmptyProductionTemplateVersion', // THIS REQUIRES TO SET DEVICE TO STAGING FOR TEST BELOW
            'emptyStagingFullProductionTemplateVersion',
        ];

        // Build provider data with device types and reinstall flags combinations cloned for every template name
        // This will result in a matrix of device types, reinstall flags, and template names
        // Each template name will be tested with all device types and reinstall flags combinations
        $providerData = DeviceCommunicationTestMatrixBuilder::withParameter(
            'templateName',
            DeviceCommunicationTestMatrixBuilder::normalizeValues($templateNames),
            DeviceCommunicationTestMatrixBuilder::buildDeviceTypesWithReinstallFlagsMatrix()
        );

        return $providerData;
    }

    #[DataProvider('dataProvider')]
    #[Group('DeviceSecretsAndCertificatesFullTemplateComponents')]
    public function testFullTemplateComponents(array $deviceTypeConfiguration, array $reinstallFlagsConfiguration, string $templateName): void
    {
        $this->provideDeviceTypeModel($deviceTypeConfiguration, $reinstallFlagsConfiguration);

        $this->executeInitialDeviceCreationRequest();

        $deviceId = $this->getRequiredProvidedEntityParameter(DeviceModel::class, 'id');
        $this->loginApi('admin', 'admin');
        $this->getApiClient()->request(
            uri: '/web/api/device/{id}/enable',
            uriParameters: [
                'id' => $deviceId,
            ],
        );

        $this->provideDeviceState();
        // Asserting correct state of secrets and certificates
        $this->assertDeviceCertificatesState(false);
        $this->assertDeviceSecretsExists(
            expectAutoGenerated: false,
            expectAll: false,
        );

        $this->updateDeviceWithReinstallFlags($reinstallFlagsConfiguration);

        if ('fullStagingEmptyProductionTemplateVersion' === $templateName || 'fullStagingTemplateVersion' === $templateName) {
            $this->setDeviceToStaging();
        }

        // Secondary pass with fullBothTemplateVersion to also check if staging template works correctly
        if ('fullBothTemplateVersionForStaging' === $templateName) {
            $this->setDeviceToStaging();
            $templateName = 'fullBothTemplateVersion';
        }

        $this->assignTemplate($templateName);

        // *** Request on only autogenerated secrets and certificates */
        // ? Requesting again to check that device handled generate or renew of secrets and certificates as expected
        $this->executeDeviceRequestOnEnabledDevice(expectedDeviceConnectionAmount: 1);

        $expectedProcessedReinstallFlag = $this->getExpectedProcessedReinstallFlag($reinstallFlagsConfiguration);
        $expectedReinstallFlagsConfiguration = $this->getExpectedReinstallFlagsConfiguration($reinstallFlagsConfiguration, $expectedProcessedReinstallFlag);
        $this->assertDeviceReinstallFlags($expectedReinstallFlagsConfiguration);

        $expectDeviceSecretsGeneration = $this->isDeviceSecretsExpected(
            $this->isDeviceSecretsOrCertificatesGenerationOrRenewalExpected($expectedProcessedReinstallFlag)
        );

        // Asserting correct state of secrets and certificates
        $this->assertDeviceCertificatesState(false);
        $this->assertDeviceSecretsExists(
            expectAutoGenerated: $expectDeviceSecretsGeneration,
            expectAll: false,
        );

        // *** Request on only autogenerated secrets and certificates - secrets are outdated - should be renewed */
        $this->provideDeviceState();
        $this->updateDeviceWithReinstallFlags($reinstallFlagsConfiguration);
        $this->makeDeviceSecretsOutdates();

        // ? This test will execute request on enabled device with auto generated secrets which should be renewed
        $this->executeDeviceRequestOnEnabledDevice(expectedDeviceConnectionAmount: 2);

        $expectedProcessedReinstallFlag = $this->getExpectedProcessedReinstallFlag($reinstallFlagsConfiguration);
        $expectedReinstallFlagsConfiguration = $this->getExpectedReinstallFlagsConfiguration($reinstallFlagsConfiguration, $expectedProcessedReinstallFlag);
        $this->assertDeviceReinstallFlags($expectedReinstallFlagsConfiguration);

        $expectDeviceSecretsGeneration = $this->isDeviceSecretsExpected(
            $this->isDeviceSecretsOrCertificatesGenerationOrRenewalExpected($expectedProcessedReinstallFlag)
        );

        // Asserting correct state of secrets and certificates
        $this->assertDeviceCertificatesState(false);
        $this->assertDeviceSecretsExists(
            expectAutoGenerated: $expectDeviceSecretsGeneration,
            expectAll: false,
        );
        $this->assertDeviceSecretsState(true);

        // *** Request on all secrets and certificates created - should NOT be renewed */
        $this->updateDeviceWithReinstallFlags($reinstallFlagsConfiguration);
        $this->generateAllDeviceSecrets();
        $this->generateAllDeviceCertificates();
        $this->provideDeviceState();

        // ? Requesting again to check that device handled generate or renew of secrets and certificates as expected
        $this->executeDeviceRequestOnEnabledDevice(expectedDeviceConnectionAmount: 3);

        $expectedProcessedReinstallFlag = $this->getExpectedProcessedReinstallFlag($reinstallFlagsConfiguration);
        $expectedReinstallFlagsConfiguration = $this->getExpectedReinstallFlagsConfiguration($reinstallFlagsConfiguration, $expectedProcessedReinstallFlag);
        $this->assertDeviceReinstallFlags($expectedReinstallFlagsConfiguration);

        // Asserting correct state of secrets and certificates
        $this->assertDeviceCertificatesState(false);
        $this->assertDeviceSecretsExists(
            expectAutoGenerated: false,
            expectAll: $this->isDeviceSecretsExpected(true),
        );
        $this->assertDeviceSecretsState(false);

        // *** Request on all secrets and certificates created - secrets and certificates are outdated - should be renewed */
        $this->updateDeviceWithReinstallFlags($reinstallFlagsConfiguration);
        $this->provideDeviceState();
        $this->makeDeviceSecretsOutdates();
        $this->makeDeviceCertificatesOutdates();

        // ? Requesting again to check that device handled generate or renew of secrets and certificates as expected
        $this->executeDeviceRequestOnEnabledDevice(expectedDeviceConnectionAmount: 4);

        $expectedProcessedReinstallFlag = $this->getExpectedProcessedReinstallFlag($reinstallFlagsConfiguration);
        $expectedReinstallFlagsConfiguration = $this->getExpectedReinstallFlagsConfiguration($reinstallFlagsConfiguration, $expectedProcessedReinstallFlag);
        $this->assertDeviceReinstallFlags($expectedReinstallFlagsConfiguration);

        $expectDeviceCertificatesRenewal = $this->isDeviceCertificatesExpected(
            $this->isDeviceSecretsOrCertificatesGenerationOrRenewalExpected($expectedProcessedReinstallFlag)
        );

        $expectDeviceSecretsRenewal = $this->isDeviceSecretsExpected(
            $this->isDeviceSecretsOrCertificatesGenerationOrRenewalExpected($expectedProcessedReinstallFlag)
        );

        // Asserting correct state of secrets and certificates
        $this->assertDeviceCertificatesState($expectDeviceCertificatesRenewal);
        $this->assertDeviceSecretsExists(
            expectAutoGenerated: false,
            expectAll: $this->isDeviceSecretsExpected(true),
        );
        $this->assertDeviceSecretsState($expectDeviceSecretsRenewal);
    }
}
