<?php

// Copyright (c) 2025 Contributors to the Eclipse Foundation.
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache License, Version 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0

declare(strict_types=1);

namespace Tests\Suites\DeviceCommunication\DeviceSecretsAndCertificates;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Group;
use Tests\DataFixtures as TestFixtures;
use Tests\Utilities\Builder\DeviceCommunicationTestMatrixBuilder;
use Tests\Utilities\DeviceCommunicationAbstract\AbstractDeviceCommunicationTestCase;
use Tests\Utilities\DeviceCommunicationAbstract\Trait\DeviceSecretsAndCertificatesTrait;
use Tests\Utilities\DeviceCommunicationApiClient\DeviceCommunicationApiClientAssert;
use Tests\Utilities\DeviceCommunicationApiClient\Enum\DeviceCommunicationRequestTypeEnum;
use Tests\Utilities\DeviceCommunicationApiClient\Model\DeviceModel;

// This class tests the initial device creation process, against device secrets and certificates
// It checks that the device can be created with the correct secrets and certificates based on the device type configuration
// Performs a test for device without any template - when device is enabled and disabled.

class NoTemplateTest extends AbstractDeviceCommunicationTestCase
{
    use DeviceSecretsAndCertificatesTrait;

    public static function getFixtureGroups(): array
    {
        return \array_merge(
            parent::getFixtureGroups(),
            [
                TestFixtures\DeviceCommunication\DeviceSecretsAndCertificates\DeviceTypeCommunicationProcedureFixtures::class,
            ],
        );
    }

    // Data provider combines device types for provider with all possible reinstall flags combinations
    public static function dataProvider(): array
    {
        return DeviceCommunicationTestMatrixBuilder::buildDeviceTypesWithReinstallFlagsMatrix();
    }

    #[DataProvider('dataProvider')]
    #[Group('DeviceSecretsAndCertificatesDisabledDevice')]
    public function testDisabledDevice(array $deviceTypeConfiguration, array $reinstallFlagsConfiguration): void
    {
        $this->provideDeviceTypeModel($deviceTypeConfiguration, $reinstallFlagsConfiguration);

        $this->executeInitialDeviceCreationRequest();

        $this->updateDeviceWithReinstallFlags($reinstallFlagsConfiguration);

        // ? Requesting again to check that device is created and disabled - responds with expected disabled device response
        // Secrets and certificates are not created because device is disabled
        // Checking that device accumulated connections amount correctly
        $this->getApiClient()->requestDeviceCommunication(
            requestType: DeviceCommunicationRequestTypeEnum::DISABLED,
            variables: [
              'expectedDeviceConnectionAmount' => 0,
            ],
            asserts: [
                // Asserting that device entity exists in database (was created), and is disabled
                // Also asserting that device entity does not have any device secrets and certificates - because it is disabled, so none of them should be created
                // Also asserting propper amount of device connections
                DeviceCommunicationApiClientAssert::DEVICE_ENTITY_EXISTS_WITHOUT_DEVICE_SECRETS,
                DeviceCommunicationApiClientAssert::DEVICE_ENTITY_EXISTS_WITHOUT_DEVICE_CERTIFICATES,
                DeviceCommunicationApiClientAssert::DEVICE_CONNECTIONS_AMOUNT_COUNT,
            ],
        );

        $this->assertDeviceReinstallFlags($reinstallFlagsConfiguration);

        // *** Request on all secrets and certificates created - secrets and certificates are outdated - BUT should NOT be renewed */
        $this->updateDeviceWithReinstallFlags($reinstallFlagsConfiguration);
        $this->generateAllDeviceSecrets();
        $this->generateAllDeviceCertificates();

        $this->provideDeviceState();

        $this->makeDeviceSecretsOutdates();
        $this->makeDeviceCertificatesOutdates();

        // ? Requesting again to check that device handled generate or renew of secrets and certificates as expected
        $this->executeDeviceDisabledRequest(expectedDeviceConnectionAmount: 0);

        // Asserting no additional secrets and certificates were created or renewed
        $this->assertDeviceCertificatesState(false);
        $this->assertDeviceSecretsExists(
            expectAutoGenerated: false,
            expectAll: $this->isDeviceSecretsExpected(true),
        );

        $this->assertDeviceSecretsState(false);
    }

    #[DataProvider('dataProvider')]
    #[Group('DeviceSecretsAndCertificatesEnabledDevice')]
    public function testEnabledDevice(array $deviceTypeConfiguration, array $reinstallFlagsConfiguration): void
    {
        $this->provideDeviceTypeModel($deviceTypeConfiguration, $reinstallFlagsConfiguration);

        $this->executeInitialDeviceCreationRequest();

        $deviceId = $this->getRequiredProvidedEntityParameter(DeviceModel::class, 'id');
        $this->loginApi('admin', 'admin');
        $this->getApiClient()->request(
            uri: '/web/api/device/{id}/enable',
            uriParameters: [
                'id' => $deviceId,
            ],
        );

        $this->provideDeviceState();

        // Asserting correct state of secrets and certificates - only auto-generated certificates should be created
        $this->assertDeviceCertificatesState(false);
        $this->assertDeviceSecretsExists(
            expectAutoGenerated: false,
            expectAll: false,
        );

        $this->updateDeviceWithReinstallFlags($reinstallFlagsConfiguration);

        // ? Requesting again to check that enabled device still didn't generate or renew any secrets and certificates
        $this->executeDeviceRequestOnEnabledDevice(expectedDeviceConnectionAmount: 1);

        // Asserting no additional secrets and certificates were created or renewed
        $this->assertDeviceCertificatesState(false);
        $this->assertDeviceSecretsExists(
            expectAutoGenerated: $this->isDeviceSecretsExpected(false),
            expectAll: false,
        );

        $this->assertDeviceReinstallFlags($reinstallFlagsConfiguration);

        // *** Request on all secrets and certificates created - secrets and certificates are outdated - BUT should NOT be renewed */
        $this->updateDeviceWithReinstallFlags($reinstallFlagsConfiguration);
        $this->generateAllDeviceSecrets();
        $this->generateAllDeviceCertificates();

        $this->provideDeviceState();

        $this->makeDeviceSecretsOutdates();
        $this->makeDeviceCertificatesOutdates();

        // ? Requesting again to check that device handled generate or renew of secrets and certificates as expected
        $this->executeDeviceRequestOnEnabledDevice(expectedDeviceConnectionAmount: 2);

        // Asserting no additional secrets and certificates were created or renewed
        $this->assertDeviceCertificatesState($this->isDeviceCertificatesExpected(false));
        $this->assertDeviceSecretsExists(
            expectAutoGenerated: false,
            expectAll: $this->isDeviceSecretsExpected(true),
        );

        $this->assertDeviceSecretsState($this->isDeviceCertificatesExpected(false));
    }
}
