name: "Update image version, build, push and git add"
description: "Update image version, build, push and git add"

inputs:
    name:
        description: "Image name (lowercase)"
        required: true
    version:
        description: "Image version"
        required: true

runs:
    using: "composite"
    steps:
        - name: Image "${{ inputs.name }}" - Verify existing image
          shell: bash
          id: exists
          continue-on-error: true
          run: |
              source "docker/images/${{ inputs.name }}/.env"
              IMAGE="${{ inputs.name }}"
              IMAGE_UPPERCASE="${IMAGE^^}"

              REGISTRY_IMAGE_VAR="${IMAGE_UPPERCASE}_REGISTRY_IMAGE"
              VERSION_VAR="${IMAGE_UPPERCASE}_VERSION"

              docker manifest inspect "${!REGISTRY_IMAGE_VAR}:${{ inputs.version }}" >/dev/null 2>&1

        - name: Image "${{ inputs.name }}" - Image exists, abort
          if: steps.exists.outcome == 'success'
          shell: bash
          run: |
              echo "Image '${{ inputs.name }}' version '${{ inputs.version }}' already exists. Aborting."
              exit 1

        - name: Image "${{ inputs.name }}" - Update version
          shell: bash
          run: |
              IMAGE="${{ inputs.name }}"
              IMAGE_UPPERCASE="${IMAGE^^}"

              sed -i "s/^${IMAGE_UPPERCASE}_VERSION=.*/${IMAGE_UPPERCASE}_VERSION=${{ inputs.version }}/" "docker/images/${{ inputs.name }}/.env"

        - name: Image "${{ inputs.name }}" - Build
          shell: bash
          run: |
              make ${{ inputs.name }}-build

        - name: Image "${{ inputs.name }}" - Push
          shell: bash
          run: |
              make ${{ inputs.name }}-push

        - name: Image "${{ inputs.name }}" - Git add
          shell: bash
          run: |
              git add docker/images/${{ inputs.name }}/.env
