name: "Update image version, build, push and git add"
description: "Update image version, build, push and git add"

inputs:
    name:
        description: "Image name (lowercase)"
        required: true
    version:
        description: "Image version"
        required: true

runs:
    using: "composite"
    steps:
        - name: Image "${{ inputs.name }}" - Update version
          run: |
              sed -i "s/^${${{ inputs.name }}^^}_VERSION=.*/${${{ inputs.name }}^^}_VERSION=${{ inputs.version }}/" "docker/images/${{ inputs.name }}/.env"

        - name: Image "${{ inputs.name }}" - Build
          run: |
              make ${{ inputs.name }}-build

        - name: Image "${{ inputs.name }}" - Push
          run: |
              make ${{ inputs.name }}-push

        - name: Image "${{ inputs.name }}" - Git add
          run: |
              git add docker/images/${{ inputs.name }}/.env

branding:
    color: "blue"
    icon: "package"
