# Copyright (c) 2025 Contributors to the Eclipse Foundation.
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

api_login_check:
    path: /web/api/authentication/login_check

api_refresh_token:
    path: /web/api/authentication/token/refresh

api_refresh_token_invalidate:
    path: /web/api/authenticated/logout

api_refresh_token_keep_ttl:
    path: /web/api/authentication/token/keep-ttl-refresh

api_download_auth_admin:
    path: /web/api/check/auth/admin
    controller: App\Controller\DownloadSecurityAdminController::checkAuthAction

api_download_auth_firmware:
    path: /web/api/check/auth/firmware
    controller: App\Controller\DownloadSecurityFirmwareController::checkAuthAction

device_download_auth_firmware:
    path: /device/check/auth/firmware
    controller: App\Controller\DeviceDownloadSecurityFirmwareController::checkAuthAction
