# Copyright (c) 2025 Contributors to the Eclipse Foundation.
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

name: Pull request CI/CD

on:
    pull_request:
        branches:
            - "**"

jobs:
    detect-and-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Detect changed images
              id: changes
              uses: dorny/paths-filter@v3
              with:
                  filters: .github/path-filters.yaml

            - name: Update changed image versions
              run: |
                  ./.github/scripts/update_image_version.sh "core" "${GITHUB_SHA}" "${{ steps.changes.outputs.core }}"
                  ./.github/scripts/update_image_version.sh "composer" "${GITHUB_SHA}" "${{ steps.changes.outputs.composer }}"
                  ./.github/scripts/update_image_version.sh "scep" "${GITHUB_SHA}" "${{ steps.changes.outputs.scep }}"
                  ./.github/scripts/update_image_version.sh "backend" "${GITHUB_SHA}" "${{ steps.changes.outputs.core }}"
                  ./.github/scripts/update_image_version.sh "backend" "${GITHUB_SHA}" "${{ steps.changes.outputs.composer }}"
                  ./.github/scripts/update_image_version.sh "backend" "${GITHUB_SHA}" "${{ steps.changes.outputs.backend }}"
                  ./.github/scripts/update_image_version.sh "frontend" "${GITHUB_SHA}" "${{ steps.changes.outputs.frontend }}"
                  ./.github/scripts/update_image_version.sh "app" "${GITHUB_SHA}" "${{ steps.changes.outputs.core }}"
                  ./.github/scripts/update_image_version.sh "app" "${GITHUB_SHA}" "${{ steps.changes.outputs.scep }}"
                  ./.github/scripts/update_image_version.sh "app" "${GITHUB_SHA}" "${{ steps.changes.outputs.backend }}"
                  ./.github/scripts/update_image_version.sh "app" "${GITHUB_SHA}" "${{ steps.changes.outputs.frontend }}"
                  ./.github/scripts/update_image_version.sh "app" "${GITHUB_SHA}" "${{ steps.changes.outputs.composer }}"
                  ./.github/scripts/update_image_version.sh "app" "${GITHUB_SHA}" "${{ steps.changes.outputs.app }}"
                  ./.github/scripts/update_image_version.sh "test" "${GITHUB_SHA}" "true"

            - name: Build changed images
              run: |
                  ./.github/scripts/build_docker_image.sh "core" "${{ steps.changes.outputs.core }}"
                  ./.github/scripts/build_docker_image.sh "composer" "${{ steps.changes.outputs.composer }}"
                  ./.github/scripts/build_docker_image.sh "scep" "${{ steps.changes.outputs.scep }}"
                  ./.github/scripts/build_docker_image.sh "backend" "${{ steps.changes.outputs.backend }}"
                  ./.github/scripts/build_docker_image.sh "frontend" "${{ steps.changes.outputs.frontend }}"
                  ./.github/scripts/build_docker_image.sh "app" "${{ steps.changes.outputs.app }}"
                  ./.github/scripts/build_docker_image.sh "test" "${{ steps.changes.outputs.app }}"

            - name: Run smoke tests
              # docker compose -f docker/deployments/test/compose.yaml exec application php vendor/bin/phpunit --group smoke
              run: |
                  docker compose -f docker/deployments/test/compose.yaml up
