# Copyright (c) 2025 Contributors to the Eclipse Foundation.
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

name: Release CI/CD

on:
    push:
        branches:
            # TODO
            # - "release/*"
            - "i-1/release"

jobs:
    changes:
        runs-on: ubuntu-latest
        outputs:
            release: ${{ steps.release.outputs.release }}
            core: ${{ steps.changes.outputs.core }}
            composer: ${{ steps.changes.outputs.composer }}
            scep: ${{ steps.changes.outputs.scep }}
            backend: ${{ steps.changes.outputs.backend }}
            frontend: ${{ steps.changes.outputs.frontend }}
            app: ${{ steps.changes.outputs.app }}
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Detect changed version
              id: version
              uses: dorny/paths-filter@v3
              with:
                  base: "${{ github.ref }}"
                  filters: |
                      version:
                          - ".github/metadata/PREVIOUS_VERSION"
                          - ".github/metadata/VERSION"

            - name: Detect release metadata
              id: release
              run: |
                  ./.github/scripts/detect_release_metadata.sh "${{ steps.version.outputs.version }}"

            - name: Detect changed images
              id: changes
              uses: dorny/paths-filter@v3
              with:
                  base: ${{ steps.release.outputs.changesBase }}
                  filters: .github/path-filters.yaml

    no-release:
        needs: changes
        if: needs.changes.outputs.release == 'no'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Update changed image versions
              if: needs.changes.outputs.app == 'true'
              run: |
                  ./.github/scripts/update_image_version.sh "core" "${GITHUB_SHA}" "${{ needs.changes.outputs.core }}"
                  ./.github/scripts/update_image_version.sh "composer" "${GITHUB_SHA}" "${{ needs.changes.outputs.composer }}"
                  ./.github/scripts/update_image_version.sh "scep" "${GITHUB_SHA}" "${{ needs.changes.outputs.scep }}"
                  ./.github/scripts/update_image_version.sh "backend" "${GITHUB_SHA}" "${{ needs.changes.outputs.backend }}"
                  ./.github/scripts/update_image_version.sh "frontend" "${GITHUB_SHA}" "${{ needs.changes.outputs.frontend }}"
                  ./.github/scripts/update_image_version.sh "app" "${GITHUB_SHA}" "${{ needs.changes.outputs.app }}"
                  ./.github/scripts/update_image_version.sh "test" "${GITHUB_SHA}" "${{ needs.changes.outputs.app }}"

            - name: Login to GHCR
              uses: docker/login-action@v3
              if: needs.changes.outputs.app == 'true'
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build changed images
              if: needs.changes.outputs.app == 'true'
              run: |
                  ./.github/scripts/build_docker_image.sh "core" "${{ needs.changes.outputs.core }}"
                  ./.github/scripts/build_docker_image.sh "composer" "${{ needs.changes.outputs.composer }}"
                  ./.github/scripts/build_docker_image.sh "scep" "${{ needs.changes.outputs.scep }}"
                  ./.github/scripts/build_docker_image.sh "backend" "${{ needs.changes.outputs.backend }}"
                  ./.github/scripts/build_docker_image.sh "frontend" "${{ needs.changes.outputs.frontend }}"
                  ./.github/scripts/build_docker_image.sh "app" "${{ needs.changes.outputs.app }}"
                  ./.github/scripts/build_docker_image.sh "test" "${{ needs.changes.outputs.app }}"

            - name: Run smoke tests
              if: steps.changes.outputs.app == 'true'
              run: |
                  echo "APPLICATION_ENV=test" >> docker/deployments/test/.env
                  echo "APPLICATION_PHP_MEMORY_LIMIT=\"-1\"" >> docker/deployments/test/.env
                  echo "APPLICATION_VERSION=${GITHUB_SHA}" >> docker/deployments/test/.env
                  docker compose -f docker/deployments/test/compose.yaml up -d
                  docker/deployments/test/wait-until-ready.sh
                  docker compose -f docker/deployments/test/compose.yaml exec application php bin/phpunit --group smoke

    release-candidate:
        needs: changes
        if: needs.changes.outputs.release == 'rc'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Test RC
              run: |
                  echo "RC"

    production-release:
        needs: changes
        if: needs.changes.outputs.release == 'production'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Test production
              run: |
                  echo "Production"
