# Copyright (c) 2025 Contributors to the Eclipse Foundation.
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

name: Release CI/CD

on:
    push:
        branches:
            # TODO
            # - "release/*"
            - "i-1/release"

jobs:
    changes:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.release.outputs.version }}
            release: ${{ steps.release.outputs.release }}
            core: ${{ steps.changes.outputs.core }}
            composer: ${{ steps.changes.outputs.composer }}
            scep: ${{ steps.changes.outputs.scep }}
            backend: ${{ steps.changes.outputs.backend }}
            frontend: ${{ steps.changes.outputs.frontend }}
            app: ${{ steps.changes.outputs.app }}
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Detect changed version
              id: version
              uses: dorny/paths-filter@v3
              with:
                  base: "${{ github.ref }}"
                  filters: |
                      version:
                          - ".github/metadata/PREVIOUS_VERSION"
                          - ".github/metadata/VERSION"

            - name: Detect release metadata
              id: release
              run: |
                  ./.github/scripts/detect_release_metadata.sh "${{ steps.version.outputs.version }}"

            - name: Detect changed images
              id: changes
              uses: dorny/paths-filter@v3
              with:
                  base: ${{ steps.release.outputs.changesBase }}
                  filters: .github/path-filters.yaml

    release-none:
        needs: changes
        if: needs.changes.outputs.release == 'none' && needs.changes.outputs.app == 'true'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build "core" image
              uses: ./.github/actions/image-build
              if: needs.changes.outputs.core == 'true'
              with:
                  name: "core"
                  version: "${GITHUB_SHA}"

            - name: Build "composer" image
              uses: ./.github/actions/image-build
              if: needs.changes.outputs.composer == 'true'
              with:
                  name: "composer"
                  version: "${GITHUB_SHA}"

            - name: Build "scep" image
              uses: ./.github/actions/image-build
              if: needs.changes.outputs.scep == 'true'
              with:
                  name: "scep"
                  version: "${GITHUB_SHA}"

            - name: Build "cobackendmposer" image
              uses: ./.github/actions/image-build
              if: needs.changes.outputs.backend == 'true'
              with:
                  name: "backend"
                  version: "${GITHUB_SHA}"

            - name: Build "frontend" image
              uses: ./.github/actions/image-build
              if: needs.changes.outputs.frontend == 'true'
              with:
                  name: "frontend"
                  version: "${GITHUB_SHA}"

            - name: Build "app" image
              uses: ./.github/actions/image-build
              if: needs.changes.outputs.app == 'true'
              with:
                  name: "app"
                  version: "${GITHUB_SHA}"

            - name: Build "test" image
              uses: ./.github/actions/image-build
              if: needs.changes.outputs.app == 'true'
              with:
                  name: "test"
                  version: "${GITHUB_SHA}"

            - name: PHPUnit smoke tests
              uses: ./.github/actions/phpunit
              if: needs.changes.outputs.app == 'true'
              with:
                  version: "${GITHUB_SHA}"
                  group: "smoke"

    release-initial:
        needs: changes
        if: needs.changes.outputs.release == 'initial'
        permissions:
            contents: write
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Update changed image versions
              run: |
                  ./.github/scripts/update_image_version.sh "core" "${{ needs.changes.outputs.version }}" "true"
                  ./.github/scripts/update_image_version.sh "composer" "${{ needs.changes.outputs.version }}" "true"
                  ./.github/scripts/update_image_version.sh "scep" "${{ needs.changes.outputs.version }}" "true"
                  ./.github/scripts/update_image_version.sh "backend" "${{ needs.changes.outputs.version }}" "true"
                  ./.github/scripts/update_image_version.sh "frontend" "${{ needs.changes.outputs.version }}" "true"
                  ./.github/scripts/update_image_version.sh "app" "${{ needs.changes.outputs.version }}" "true"
                  ./.github/scripts/update_image_version.sh "test" "${{ needs.changes.outputs.version }}" "true"

            - name: Build changed images
              run: |
                  ./.github/scripts/build_docker_image.sh "core" "true"
                  ./.github/scripts/build_docker_image.sh "composer" "true"
                  ./.github/scripts/build_docker_image.sh "scep" "true"
                  ./.github/scripts/build_docker_image.sh "backend" "true"
                  ./.github/scripts/build_docker_image.sh "frontend" "true"
                  ./.github/scripts/build_docker_image.sh "app" "true"
                  ./.github/scripts/build_docker_image.sh "test" "true"

            - name: Push updated images
              run: |
                  ./.github/scripts/push_docker_image.sh "core" "true"
                  ./.github/scripts/push_docker_image.sh "composer" "true"
                  ./.github/scripts/push_docker_image.sh "scep" "true"
                  ./.github/scripts/push_docker_image.sh "backend" "true"
                  ./.github/scripts/push_docker_image.sh "frontend" "true"
                  ./.github/scripts/push_docker_image.sh "app" "true"

            # - name: Test git commit push
            #   run: |
            #       touch testfile.txt
            #       echo "Test" >> testfile.txt
            #       git config user.name sealman-github-actions
            #       git config user.email sealman-github-actions@github.com
            #       git add testfile.txt
            #       git commit -m "Test commit from GitHub Actions"
            #       git push origin ${{ github.head_ref }}
            # TODO also update and commit .env files in docker images

    release-rc:
        needs: changes
        if: needs.changes.outputs.release == 'rc'
        permissions:
            contents: write
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker "core" image - update version, build, push, git add
              if: needs.changes.outputs.core == 'true'
              run: |
                  sed -i "s/^CORE_VERSION=.*/CORE_VERSION=${{ needs.changes.outputs.version }}/" "docker/images/core/.env"
                  make core-build
                  make core-push
                  git add docker/images/core/.env

            - name: Docker "composer" image - update version, build, push, git add
              if: needs.changes.outputs.composer == 'true'
              run: |
                  sed -i "s/^COMPOSER_VERSION=.*/COMPOSER_VERSION=${{ needs.changes.outputs.version }}/" "docker/images/composer/.env"
                  make composer-build
                  make composer-push
                  git add docker/images/composer/.env

            - name: Docker "scep" image - update version, build, push, git add
              if: needs.changes.outputs.scep == 'true'
              run: |
                  sed -i "s/^SCEP_VERSION=.*/SCEP_VERSION=${{ needs.changes.outputs.version }}/" "docker/images/scep/.env"
                  make scep-build
                  make scep-push
                  git add docker/images/scep/.env

            - name: Docker "backend" image - update version, build, push, git add
              if: needs.changes.outputs.backend == 'true'
              run: |
                  sed -i "s/^BACKEND_VERSION=.*/BACKEND_VERSION=${{ needs.changes.outputs.version }}/" "docker/images/backend/.env"
                  make backend-build
                  make backend-push
                  git add docker/images/backend/.env

            - name: Docker "frontend" image - update version, build, push, git add
              if: needs.changes.outputs.frontend == 'true'
              run: |
                  sed -i "s/^FRONTEND_VERSION=.*/FRONTEND_VERSION=${{ needs.changes.outputs.version }}/" "docker/images/frontend/.env"
                  make frontend-build
                  make frontend-push
                  git add docker/images/frontend/.env

            - name: Docker "app" image - update version, build, push, git add
              if: needs.changes.outputs.app == 'true'
              run: |
                  sed -i "s/^APP_VERSION=.*/APP_VERSION=${{ needs.changes.outputs.version }}/" "docker/images/app/.env"
                  make app-build
                  make app-push
                  git add docker/images/app/.env

            - name: Docker "test" image - update version, build, push, git add
              if: needs.changes.outputs.app == 'true'
              run: |
                  sed -i "s/^TEST_VERSION=.*/TEST_VERSION=${{ needs.changes.outputs.version }}/" "docker/images/test/.env"
                  make test-build
                  make test-push
                  git add docker/images/test/.env

            - name: Git commit
              if: needs.changes.outputs.app == 'true'
              run: |
                  sed -i "s/^TEST_VERSION=.*/TEST_VERSION=${{ needs.changes.outputs.version }}/" "docker/images/test/.env"
                  make test-build
                  make test-push
                  git add docker/images/test/.env

            - name: Run full tests
              run: |
                  echo "APPLICATION_VERSION=${{ needs.changes.outputs.version }}" >> docker/deployments/test/.env
                  docker compose -f docker/deployments/test/compose.yaml up -d
                  docker/deployments/test/wait-until-ready.sh
                  docker compose -f docker/deployments/test/compose.yaml exec application php bin/phpunit --group full
                  docker compose -f docker/deployments/test/compose.yaml down

    release-production:
        needs: changes
        if: needs.changes.outputs.release == 'production'
        permissions:
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Update changed image versions
              run: |
                  ./.github/scripts/update_image_version.sh "core" "${{ needs.changes.outputs.version }}" "${{ needs.changes.outputs.core }}"
                  ./.github/scripts/update_image_version.sh "composer" "${{ needs.changes.outputs.version }}" "${{ needs.changes.outputs.composer }}"
                  ./.github/scripts/update_image_version.sh "scep" "${{ needs.changes.outputs.version }}" "${{ needs.changes.outputs.scep }}"
                  ./.github/scripts/update_image_version.sh "backend" "${{ needs.changes.outputs.version }}" "${{ needs.changes.outputs.backend }}"
                  ./.github/scripts/update_image_version.sh "frontend" "${{ needs.changes.outputs.version }}" "${{ needs.changes.outputs.frontend }}"
                  ./.github/scripts/update_image_version.sh "app" "${{ needs.changes.outputs.version }}" "${{ needs.changes.outputs.app }}"
                  ./.github/scripts/update_image_version.sh "test" "${{ needs.changes.outputs.version }}" "${{ needs.changes.outputs.app }}"

            - name: Build changed images
              run: |
                  ./.github/scripts/build_docker_image.sh "core" "${{ steps.changes.outputs.core }}"
                  ./.github/scripts/build_docker_image.sh "composer" "${{ steps.changes.outputs.composer }}"
                  ./.github/scripts/build_docker_image.sh "scep" "${{ steps.changes.outputs.scep }}"
                  ./.github/scripts/build_docker_image.sh "backend" "${{ steps.changes.outputs.backend }}"
                  ./.github/scripts/build_docker_image.sh "frontend" "${{ steps.changes.outputs.frontend }}"
                  ./.github/scripts/build_docker_image.sh "app" "${{ steps.changes.outputs.app }}"
                  ./.github/scripts/build_docker_image.sh "test" "${{ steps.changes.outputs.app }}"

            # TODO Push or retag images, also update and commit .env files in docker images
            - name: Push updated images
              run: |
                  ./.github/scripts/push_docker_image.sh "core" "${{ steps.changes.outputs.core }}"
                  ./.github/scripts/push_docker_image.sh "composer" "${{ steps.changes.outputs.composer }}"
                  ./.github/scripts/push_docker_image.sh "scep" "${{ steps.changes.outputs.scep }}"
                  ./.github/scripts/push_docker_image.sh "backend" "${{ steps.changes.outputs.backend }}"
                  ./.github/scripts/push_docker_image.sh "frontend" "${{ steps.changes.outputs.frontend }}"
                  ./.github/scripts/push_docker_image.sh "app" "${{ steps.changes.outputs.app }}"
